[TD-11995]<feature>: support remote_read and remote_write
taosdata/taosadapter pull request #24
Opened 2021-12-29 08:16 UTC by huskar-t

2021-12-29 08:42 UTC, zitsen requested changes
Please update markdown files.

2021-12-29 08:42 UTC, zitsen commented on README-CN.md
> +
Use Markdown uordered list style here.

2021-12-29 08:42 UTC, zitsen commented on README-CN.md
> +password： TDengine 连接密码
Use Markdown uordered list style here too.

2021-12-29 08:42 UTC, zitsen commented on README-CN.md
> +示例 prometheus.yml  如下：
Add line break before code .

2021-12-29 08:42 UTC, zitsen commented on README-CN.md
> +`````shell
Three ` .

2021-12-29 08:42 UTC, zitsen commented on README-CN.md
> +`````
Three "`" character ?

2021-12-29 08:42 UTC, zitsen commented on README.md
> +  [http://opentsdb.net/docs/build/html/api_http/put.html](http://opentsdb.net/docs/build/html/api_http/put.html)
Recommanded bare url style in Markdown for GitHub:

```markdown
<http://opentsdb.net/docs/build/html/api_http/put.html>
```

Rule: don't repeat yourself.

2021-12-29 08:42 UTC, zitsen commented on README.md
> +Note: There is currently not supported token authentication in InfluxDB only supports Basic authentication and query parameter authentication.
Add line break before headers/paragraphs/sections.

2021-12-29 08:42 UTC, zitsen commented on README.md
> +### prometheus
Here too.

2021-12-29 08:50 UTC, sangshuduo commented on README-CN.md
> +`````shell
多了两个 ` ？

2021-12-29 09:07 UTC, sangshuduo reviewed
see my comments

2021-12-29 09:16 UTC, huskar-t commented on README-CN.md
> +
fixed

2021-12-29 10:21 UTC, sangshuduo approved these changes
LGTM

2021-12-30 01:01 UTC, zitsen approved these changes
LGTM

2021-12-30 02:50 UTC, merged

2021-12-30 03:52 UTC, wu-champion reviewed
LGTM